#!/bin/bash

function test() {
  output=$(./bin/interpreter <<< $1)
  if [ "$output" = $2 ]; then
    echo -e "\033[1;32m \xE2\x9C\x93 \033[0m| $1 = $2"
  else
    echo -e "\033[1;31m \xE2\x9C\x97 \033[0m| $1 = $2 ($output was found) "
  fi
}

##
# DEFINE TESTS BELOW
##

# test <'formula'> <result>

test '1+10' 11
test '10-9' 1
test '4/2' 2
test '2*10' 20
test '2*10/10' 2
test '2*10+32' 52
test '4+2*4' 12
test '(4+2)*4' 24
test '-2*2-(4+2)' -10
test '4+(2*4)' 12
test '(1)+(2)' 3
test '(1+2)' 3
test '1/2/2' 0.25
test '-2' -2
test '-2+2' 0
test '-2+4-2' 0
test '-4/2' -2
test '4+-4' 0
test '5++5--5' 15
test '-(2+3)' -5
test '6^7' 279936
test '-2^2' -4
test '3^2-3^2' 0
test '2^2+3' 7
test '(2+3)^2' 25
test '2^(2+3)' 32
test 'sqrt(4)' 2
test 'pi' 3.14159
test 'cosinus(pi)' -1
test 'sin(pi)' 0
test 'plot(3*2)' 6
test 'plot(3*2, range=[-5,5])' 6
test 'plot(5^2, xrange=[2,3])' 25
test 'plot(4+2, yrange=[2,3])' 6
test 'plot(4+2, range=[-5,5], xrange=[-5,5], yrange=[2,3])' 6
